const express = require('express')
const route = express.Router()
const insWordController = require('../controller/wordController')

route.post('/insertKamatz', insWordController.insertKamatz)
route.post('/insertChirik', insWordController.insertChirik)
route.post('/insertCholam', insWordController.insertCholam)
route.post('/insertShuruk', insWordController.insertShuruk)
route.post('/insertSegol', insWordController.insertSegol)
route.post('/insertKamatzkamatz', insWordController.insertKamatzkamatz)
// route.post('/insertchirikchirik', insWordController.insertchirikchirik)
route.post('/insertchirikchirik', insWordController.insertchirikchirik)
route.post('/insertsegolsegol', insWordController.insertsegolsegol)
route.post('/insertcholamcholam', insWordController.insertcholamcholam)
route.post('/insertshurukshuruk', insWordController.insertshurukshuruk)
route.post('/insertkubutzkamatz', insWordController.insertkubutzkamatz)
route.post('/insertkamatzcholam', insWordController.insertkamatzcholam)
route.post('/insertchiriksegol', insWordController.insertchiriksegol)
route.post('/insertcholamshuruk', insWordController.insertcholamshuruk)
route.post('/insertmeorav', insWordController.insertmeorav)
route.post('/insertconsonant', insWordController.insertconsonant)

module.exports = route